package walsh_hadamard.superseded;

/**
 * Encode or decode byte arrays using the Walsh-Hadamard code.
 * @see <a href="http://en.wikipedia.org/wiki/Walsh%E2%80%93Hadamard_code">Walsh-Hadamard code on wiki</a>
 */
public interface WalshHadamard {
	/**
	 * @param message the message to be encrypted
	 * @return the cyphertext
	 */
	byte[] encrypt(byte[] message);
	/**
	 * @param cyphertext the cyphertext to be decrypted (length must be a multiple of 32, as generated by a valid encryption)
	 * @return the plaintext
	 */
	byte[] decrypt(byte[] cyphertext);
}
